"use client";
import { useEffect, useState } from "react";
import { motion, useReducedMotion } from "framer-motion";
import { ArrowDown, ArrowUp, Bot, BrainCircuit, BriefcaseBusiness, ChevronRight, Cloud, Code2, Database, Download, ExternalLink, Github, Globe2, Mail, Menu, Moon, Network, Send, ServerCog, Sparkles, Sun, X, Zap } from "lucide-react";

type Lang="en"|"ru";
const copy={
 en:{nav:["Home","About","Skills","Projects","Experience","Contact"],role:"Senior ML / LLM Engineer",intro:"Building production AI systems, RAG platforms, LLM agents and intelligent products.",view:"View projects",cv:"Download CV",about:"I design AI products that survive contact with production — from data and evaluation to reliable inference and observability.",titleAbout:"Engineering intelligence",titleSkills:"Systems I build with",titleProjects:"Selected intelligence",titleExp:"Where I made impact",titleTech:"Technology constellation",titleContact:"Let’s build what’s next",contact:"Have a hard AI problem or an ambitious product? I’m always open to a thoughtful conversation.",talk:"Let's talk"},
 ru:{nav:["Главная","Обо мне","Навыки","Проекты","Опыт","Контакты"],role:"Senior ML / LLM Engineer",intro:"Создаю промышленные AI-системы, RAG-платформы, LLM-агентов и интеллектуальные продукты.",view:"Смотреть проекты",cv:"Скачать CV",about:"Проектирую AI-продукты, готовые к реальной эксплуатации — от данных и оценки до надёжного инференса и мониторинга.",titleAbout:"Инженерия интеллекта",titleSkills:"Системы, которые я создаю",titleProjects:"Избранные проекты",titleExp:"Где я создавал ценность",titleTech:"Созвездие технологий",titleContact:"Создадим будущее вместе",contact:"Есть сложная AI-задача или амбициозный продукт? Я всегда открыт к содержательному разговору.",talk:"Обсудить проект"}
};
const skills=[{name:"AI & LLM",icon:BrainCircuit,items:["LangGraph","LangChain","RAG","AI Agents"]},{name:"Backend",icon:Code2,items:["Python","FastAPI","Kafka","REST"]},{name:"Cloud",icon:Cloud,items:["Kubernetes","Docker","AWS","Vercel"]},{name:"Data",icon:Database,items:["Qdrant","PostgreSQL","Redis","Vector DB"]},{name:"MLOps",icon:ServerCog,items:["PyTorch","HuggingFace","CI/CD","Tracing"]}];
const projects=[
 {n:"AI Assistant",k:"01",d:"Multi-agent workspace that plans, reasons and executes complex business workflows.",t:["LangGraph","FastAPI","OpenAI"]},
 {n:"RAG Platform",k:"02",d:"Enterprise knowledge retrieval with hybrid search, reranking and evaluation loops.",t:["Qdrant","Python","Kubernetes"]},
 {n:"Trend Detection",k:"03",d:"Real-time signals engine that turns noisy data streams into actionable trends.",t:["Kafka","NLP","PyTorch"]},
 {n:"Knowledge Assistant",k:"04",d:"Secure conversational access to distributed corporate knowledge.",t:["RAG","PostgreSQL","LLM"]}
];
const tech=["Python","FastAPI","Docker","Kubernetes","LangChain","LangGraph","OpenAI","Qdrant","PostgreSQL","Redis","Kafka","PyTorch","HuggingFace"];
const reveal={initial:{opacity:0,y:30},whileInView:{opacity:1,y:0},viewport:{once:true,margin:"-80px"},transition:{duration:.65}};

function NeuralOrb(){return <motion.div className="orb" animate={{y:[0,-12,0],rotate:[0,2,0]}} transition={{duration:7,repeat:Infinity,ease:"easeInOut"}} aria-hidden="true"><div className="orb-ring r1"/><div className="orb-ring r2"/><div className="core"><BrainCircuit size={72}/></div>{[0,1,2,3,4,5].map(i=><i key={i} style={{"--i":i} as React.CSSProperties}/>)}</motion.div>}
function SectionTitle({eyebrow,title}:{eyebrow:string,title:string}){return <div className="section-title"><span>{eyebrow}</span><h2>{title}</h2></div>}

export default function Portfolio(){
 const [lang,setLang]=useState<Lang>("en"),[light,setLight]=useState(false),[open,setOpen]=useState(false),[active,setActive]=useState("home"),[loaded,setLoaded]=useState(false); const reduced=useReducedMotion(); const c=copy[lang];
 useEffect(()=>{setLoaded(true); import("lenis").then(({default:Lenis})=>{if(reduced)return;const lenis=new Lenis({duration:1.1});let id=0;const raf=(t:number)=>{lenis.raf(t);id=requestAnimationFrame(raf)};id=requestAnimationFrame(raf);return()=>{cancelAnimationFrame(id);lenis.destroy()}})},[reduced]);
 useEffect(()=>{const ids=["home","about","skills","projects","experience","contact"];const o=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&setActive(e.target.id)),{rootMargin:"-40% 0px -55%"});ids.forEach(id=>{const el=document.getElementById(id);if(el)o.observe(el)});return()=>o.disconnect()},[]);
 const go=(id:string)=>{document.getElementById(id)?.scrollIntoView({behavior:"smooth"});setOpen(false)};
 return <main className={light?"light":""}>
  {!loaded&&<div className="preloader"><span>NB//SYS</span><div/></div>}
  <div className="background" aria-hidden="true"><div className="grid"/><div className="glow g1"/><div className="glow g2"/><div className="noise"/></div>
  <nav className="nav" aria-label="Primary navigation"><button className="logo" onClick={()=>go("home")} aria-label="Home">NB<span>.</span></button><div className={open?"navlinks open":"navlinks"}>{c.nav.map((n,i)=>{const id=["home","about","skills","projects","experience","contact"][i];return <button key={id} className={active===id?"active":""} onClick={()=>go(id)}>{n}</button>})}</div><div className="nav-actions"><button onClick={()=>setLang(lang==="en"?"ru":"en")} aria-label="Switch language"><Globe2/>{lang.toUpperCase()}</button><button onClick={()=>setLight(!light)} aria-label="Switch theme">{light?<Moon/>:<Sun/>}</button><button className="burger" onClick={()=>setOpen(!open)} aria-label="Menu">{open?<X/>:<Menu/>}</button></div></nav>
  <section id="home" className="hero"><motion.div {...reveal} className="hero-copy"><p className="status"><i/> AVAILABLE FOR SELECT PROJECTS</p><h1>NIKITA<br/><span>BABKIN</span></h1><h2>{c.role}</h2><p className="lead">{c.intro}</p><div className="buttons"><button className="primary" onClick={()=>go("projects")}>{c.view}<ArrowDown/></button><a className="secondary" href="/nikita-babkin-cv.pdf" download>{c.cv}<Download/></a></div></motion.div><div className="hero-art"><NeuralOrb/><span className="data d1">NEURAL CORE<br/>ONLINE</span><span className="data d2">LATENCY<br/>32MS</span></div><span className="scroll">SCROLL TO EXPLORE <ArrowDown/></span></section>
  <section id="about"><motion.div {...reveal}><SectionTitle eyebrow="01 / ABOUT" title={c.titleAbout}/><div className="about-grid"><div className="glass about-copy"><Sparkles/><p>{c.about}</p><div className="chips">{["LLM","RAG","AI Agents","LangGraph","Kubernetes","FastAPI"].map(x=><span key={x}>{x}</span>)}</div></div><div className="pipeline glass" aria-label="AI pipeline diagram"><div><Database/>DATA</div><ChevronRight/><div><Network/>RETRIEVE</div><ChevronRight/><div><Bot/>REASON</div><ChevronRight/><div><Zap/>SHIP</div></div></div></motion.div></section>
  <section id="skills"><motion.div {...reveal}><SectionTitle eyebrow="02 / CAPABILITIES" title={c.titleSkills}/><div className="skill-grid">{skills.map(({name,icon:Icon,items})=><article className="glass skill" key={name}><Icon/><h3>{name}</h3>{items.map(x=><span key={x}>{x}</span>)}</article>)}</div></motion.div></section>
  <section id="projects"><motion.div {...reveal}><SectionTitle eyebrow="03 / PROJECTS" title={c.titleProjects}/><div className="projects">{projects.map((p,i)=><motion.article className="project glass" key={p.n} whileHover={{y:-7}}><span className="num">{p.k}</span><div><p className="project-label">FEATURED SYSTEM</p><h3>{p.n}</h3><p>{p.d}</p><div className="chips">{p.t.map(x=><span key={x}>{x}</span>)}</div></div><div className="project-links"><a href="https://github.com" aria-label={`${p.n} GitHub`}><Github/></a><a href="#contact" aria-label={`${p.n} details`}><ExternalLink/></a></div></motion.article>)}</div></motion.div></section>
  <section id="experience"><motion.div {...reveal}><SectionTitle eyebrow="04 / EXPERIENCE" title={c.titleExp}/><div className="timeline"><article className="glass"><span>2024 — NOW</span><h3>MARS LLC</h3><h4>Senior LLM Engineer</h4><p>LLM Agents · RAG · Qdrant · LangGraph · FastAPI</p></article><article className="glass"><span>2021 — 2024</span><h3>MTS Digital</h3><h4>ML Engineer</h4><p>NER · Kafka · spaCy · LLM Parser · Production NLP</p></article></div></motion.div></section>
  <section className="tech"><motion.div {...reveal}><SectionTitle eyebrow="05 / STACK" title={c.titleTech}/><div className="tech-cloud">{tech.map((x,i)=><span key={x} style={{"--i":i} as React.CSSProperties}>{x}</span>)}</div><div className="stats">{[["6+","Years Experience"],["20+","AI Projects"],["5000+","Users"],["100+","LLM Experiments"]].map(x=><div key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div></motion.div></section>
  <section id="contact"><motion.div {...reveal} className="contact glass"><div><p className="project-label">06 / CONTACT</p><h2>{c.titleContact}</h2><p>{c.contact}</p><a className="primary" href="mailto:hello@nikita-babkin.dev">{c.talk}<Send/></a></div><div className="socials"><a href="mailto:hello@nikita-babkin.dev"><Mail/>Email</a><a href="https://linkedin.com"><BriefcaseBusiness/>LinkedIn</a><a href="https://github.com"><Github/>GitHub</a><a href="https://t.me"><Send/>Telegram</a></div></motion.div></section>
  <footer><span>© 2026 Nikita Babkin</span><span>ENGINEERED WITH INTELLIGENCE</span></footer><button className="top" onClick={()=>go("home")} aria-label="Back to top"><ArrowUp/></button>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"Person",name:"Nikita Babkin",jobTitle:"Senior ML / LLM Engineer",url:"https://nikita-babkin.dev"})}}/>
 </main>
}
